### PR TITLE
feat: do not generate policy when Expires parameter is enough

### LINKED ISSUE #4: Policy is optional
Currently Policy parameter is always generated even when it is redundant (no user ip or other options passed).
Botocore library uses either Expires or Policy parameter depending on input options: https://github.com/boto/botocore/blob/2cf64649cc020c2edcf28e22e6384750b5d8edb0/botocore/signers.py#L399-L402

This can be a big optimization for simple use cases and current behavior might not even be correct if both `Expires` and `Policy` are present with date_greater_than inside policy

### PR DESCRIPTION
**Pull request by Fogapod**
Fixes: #4 

This PR builds on top of #3 

I made `Policy` optional parameter when signing urls. It is only added when either `date_greater_than` or `ip_address` is present in options.
I compared this to botocore output for same inputs and signed url match now.
I haven't changed cookie signing because i don't use it and don't know how it works.

### CODE REVIEW

**Comment by Fogapod** [comment]
generated url does not actually match botocore and is always the same. investigating

**Comment by Fogapod** [comment]
it is resolved now

**Review by pevers — APPROVED** [review]
Hi @Fogapod ,

Sorry for the very late reply. I forgot about this PR.

This looks like a great addition and it seems to be in line what Botocore does. This PR is looking good and can be merged if you can fix the merge conflict 👍 

Thanks for your contribution!

**Comment by Fogapod** [comment]
I will fix the conflict today

**Comment by pevers** [comment]
This is great, thanks @Fogapod !

**Pull request merged**
